name: Generate NEET MCQs

on:
  workflow_dispatch: 
  schedule:
    - cron: '0 */1 * * *' # दर १ तासाने रन होईल

jobs:
  generate-questions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        # आपण गुगल शीट काढून supabase टाकले आहे
        run: pip install requests supabase

      - name: Run Script
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        # ही कमांड फाईल रन करेल (तुमच्या फाईलचे नाव generate_questions.py आहे असे गृहीत धरले आहे)
        run: python generate_questions.py
